version: "3.9"

services:

  db:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "order_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
#    volumes:
#      - .:/docker-entrypoint-initdb.d
#    ports:
#      - "5436:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  order:
    depends_on:
      - db
    image: rizomus/camunda-order
#    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - "8001:8001"
    restart: always