apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-db-deployment
spec:
  serviceName: "order-db"
  replicas: 1
  selector:
    matchLabels:
      app: order-db-deployment
  template:
    metadata:
      labels:
        app: order-db-deployment
    spec:
      containers:
          - name: postgres
            image: postgres:16-alpine
            ports:
              - containerPort: 5432
                name: postgredb
            env:
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    name: order-configmap
                    key: POSTGRES_DB

              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    name: order-configmap
                    key: POSTGRES_USER

              - name: POSTGRES_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: order-configmap
                    key: POSTGRES_PASSWORD

            volumeMounts:
              - name: postgredb
                mountPath: /var/lib/postgresql/data
                subPath: postgres

  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
