apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order-label            #должно соответствовать лейблу пода
  ports:
    - protocol: TCP
      name: web
      port: 8011          #порт сервиса
      targetPort: 8011    #порт пода (порт, который открыт у контейнера)

  type: ClusterIP
  clusterIP: None