apiVersion: v1
kind: Secret
metadata:
  name: volaand
type: Opaque
data:
  DATABASE_NAME: b3JkZXJfZGI=
  DATABASE_URL: {{ printf "jdbc:postgresql://%s:%s" .Values.service.db.host .Values.service.db.sport | b64enc }}
  DATABASE_SCHEMA: b3JkZXJfZGI=
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXMK #postgres
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXMK #postgres
